# Generated by Django 5.2.15 on 2026-06-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('response_blob', models.JSONField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Market Data Cache',
                'verbose_name_plural': 'Market Data Caches',
                'db_table': 'market_data_cache',
            },
        ),
    ]
